version: "3.8"
services:
  quotes:
    build: .
    container_name: quotes
    environment:
      - PORT=8080
      - GIN_MODE=release
      - SERVICE_NAME=quotes
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4318
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command:
      - "/bin/sh"
      - "-c"
      - "while ! nc -w 1 -z zipkin-collector 9411; do echo sleep for 1s waiting for zipkin-collector to become available; sleep 1; done && /go/bin/main -zipkin http://zipkin-collector:9411/api/v2/spans"
    depends_on:
      - zipkin-collector

  zipkin-collector:
    image: openzipkin/zipkin-slim:latest
    container_name: zipkin-collector
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.80.0
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - "--config=/etc/otel-collector-config.yaml"
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - zipkin-collector

  # go-auto:
  #   image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.10.1-alpha
  #   privileged: true
  #   pid: "host"
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
  #     - OTEL_GO_AUTO_TARGET_EXE=/usr/local/bin/main
  #     - OTEL_SERVICE_NAME=quotes
  #     - OTEL_PROPAGATORS=tracecontext,baggage,ottrace
  #   volumes:
  #     - .:/app
  #     - /proc:/host/proc
